### ISSUE TITLE
Create Digital (Carbon & Northstar) page on the Duo website

### ISSUE THREAD

**Issue by kuehndaniel** [carbon-design-system/issue-tracking#20] opened 2018-09-17 21:16 UTC
opened by Alison:

due 9/6 for TT meeting

Duo website:
https://github.ibm.com/duo/website
https://duo.w3ibm.mybluemix.net/

**Comment by kuehndaniel** [comment] 2018-09-17 21:16
From Clay:

First stab at copy for this page:

Carbon is IBM’s open-source design system for digital products and other web properties, including marketing pages. Carbon was built on the Duo foundation as a resource for designers and front-end developers, and includes a comprehensive collection of UI components and documentation, code for multiple UI frameworks, human interface guidelines, and tooling. Carbon is managed by a core team of designers, developers, and writers based in the Austin studio.

Get started with Carbon [carbondesignsystem.com]

**Comment by kuehndaniel** [comment] 2018-09-17 21:17
From Clay to Erica -

I wasn't entirely sure how to approach the Northstar-specific messaging. . . Any thoughts?

**Comment by kuehndaniel** [comment] 2018-09-17 21:17
From Erica -

So it looks like in here you're explaining Northstar within that paragraph. @Wonil-Suh1 are you okay with putting v19alpha under the carbon name at this point?

If so, the CTA's could be:
Get started with product [carbondesignsystem.com]
Get started with web and digital marketing [https://www.ibm.com/standards/web/design/]

------
If not, we need to break out the paragraphs to be something like this, but maybe not as repetitive as I have it here:

Carbon is IBM’s open-source design system for products. Carbon was built on the Duo foundation as a resource for designers and front-end developers, and includes a comprehensive collection of UI components and documentation, code for multiple UI frameworks, human interface guidelines, and tooling. Carbon is managed by a core team of designers, developers, and writers based in the Austin studio.

Get started with Carbon [carbondesignsystem.com]


Northstar is IBM's design system for web properties, including marketing pages. Northstar is built on the Duo foundation as a resource for designers and front-end developers, and includes a comprehensive collection of UI components documentation, guidelines, shared services, and tooling. Northstar is managed by a global team of designers and developers.

Get started with Northstar [https://www.ibm.com/standards/web/design/]

**Comment by kuehndaniel** [comment] 2018-09-17 21:18
From Robin -

This is secondary to #957 (which needs to be done for 9/13 town hall), but we should then implement at the latest next sprint (commencing 9/24) for completion in advance of 9/30. But can be done within current sprint.

**Comment by kuehndaniel** [comment] 2018-09-17 21:20
original issue closed but found here - https://github.ibm.com/carbon/issues/issues/899

**Comment by claycrenshaw** [comment] 2018-09-18 18:52
Can anyone elaborate on why this issue is considered blocked, and by whom? Thanks! @kuehndaniel @alisonjoseph

**Comment by alisonjoseph** [comment] 2018-09-18 19:00
Dev is waiting on a design/final content for the page as far as I  can tell? Not sure who is responsible for creating that?

**Comment by claycrenshaw** [comment] 2018-09-18 19:46
Transferring to Daniel since the continued need for this page has been called into question. . .

**Comment by claycrenshaw** [comment] 2018-09-20 21:31
@kuehndaniel Does the milestone assignment above mean that we have confirmed the need for this page?

**Comment by kuehndaniel** [comment] 2018-09-20 21:50
@claycrenshaw I believe this was covered with the IBM Design landing page, but in looking at the old Duo site there is a cross link to Carbon (will need updated Carbon linked) but not Northstar. We can verify with @jeoffw if those pieces satisfy discoverability across the pages.
<img width="394" alt="screen shot 2018-09-20 at 4 44 02 pm" src="https://user-images.githubusercontent.com/36553125/45848673-03b4f380-bcf5-11e8-8eec-ac4f263dcfd2.png">
<img width="633" alt="screen shot 2018-09-20 at 4 49 46 pm" src="https://user-images.githubusercontent.com/36553125/45848747-3eb72700-bcf5-11e8-9a35-5d3b568ea74f.png">

**Comment by shinytoyrobots** [comment] 2018-09-21 14:58
I actually think at this point we can just link to carbondesignsystem.com from the "Product" link under "Practices" on the Duo website. 

Or...that the "Product" link on the Duo website links to a page that provides a little context...and then that has a link to Carbon.

**Comment by shinytoyrobots** [comment] 2018-09-24 04:08
Requires @shinytoyrobots to confirm link to issue in Duo website internal repo.

**Comment by alisonjoseph** [comment] 2018-10-03 12:56
closing this since it will just be a link from the Duo website

**Closed by alisonjoseph** 2018-10-03 12:56 UTC
Labels: project: website, type: dev :robot:, type: docs :book:, type: visual :art:
